version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPO: "my-hf-model-ecr"
    S3_BUCKET: "648758970526-us-east-1-models"
    MODEL_TAR: "model.tar.gz"
    AWS_ACCOUNT_ID: "648758970526"

phases:
  install:
    commands:
      - echo "Installing Python deps..."
      - pip install --upgrade pip
      - pip install boto3

  # pre_build:
  #   commands:
  #     - echo "Logging into ECR..."
  #     - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  #     - echo "Checking ECR repo..."
  #     - >
  #       if ! aws ecr describe-repositories --repository-names $ECR_REPO --region $AWS_REGION >/dev/null 2>&1;
  #       then
  #         aws ecr create-repository --repository-name $ECR_REPO --region $AWS_REGION;
  #       fi
  #     - echo "Model tar already exists in S3 at s3://$S3_BUCKET/$MODEL_TAR"

  # build:
  #   commands:
  #     - echo "Building Docker image..."
  #     - docker build -t $ECR_REPO .
  #     - docker tag $ECR_REPO:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:latest

  # post_build:
  #   commands:
  #     - echo "Pushing Docker image to ECR..."
  #     - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:latest
  #     - echo "DONE: Docker image pushed to ECR successfully."
