version: 0.2

env:
  variables:
    MODEL_TAR: "model.tar.gz"

  parameter-store:
    AWS_ACCOUNT_ID: "/myapp/prod/account_id"
    ECR_REPO: "/myapp/prod/ecr_repo"
    S3_BUCKET: "/myapp/prod/s3_bucket"
    AWS_REGION: "/myapp/prod/region"

phases:
  install:
    commands:
      - echo "Installing Python Dependencies . . ."
      - pip install --upgrade pip
      - pip install boto3

  pre_build:
    commands:
      - echo "Logging Into ECR . . ."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - echo "Checking ECR Repo . . ."
      - >
        if ! aws ecr describe-repositories --repository-names $ECR_REPO --region $AWS_REGION >/dev/null 2>&1;
        then
          aws ecr create-repository --repository-name $ECR_REPO --region $AWS_REGION;
        fi
      - echo "Model TAR Exists In S3 At s3://$S3_BUCKET/$MODEL_TAR"

  build:
    commands:
      - echo "Building Docker Image . . ."
      - docker build -t $ECR_REPO .
      - docker tag $ECR_REPO:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing Docker Image To ECR . . ."
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:latest
      - echo "Docker Image Pushed To ECR Successfully."
